const { User } = require("../models");

const usersData = [
  {
    first_name: "Tim",
    last_name: "Cook",
    company: "Apple",
    email: "TimmyCoo@apple.com",
    password: "IheartApple1",
    profession: "Artificial Intelligence Engineer",
    person_or_company: "company",
    city: "cupertino",
  },
  {
    first_name: "Doug",
    last_name: "McMillon",
    company: "Walmart",
    email: "DougMcMillion@walmart.com",
    password: "IheartWalmart1",
    profession: "Web Developer",
    person_or_company: "company",
    city: "bentonville",
  },
  {
    first_name: "Darren",
    last_name: "Woods",
    company: "Exxon Mobil",
    email: "DarrenWoods@exxon.com",
    password: "IheartExxon1",
    profession: "Data Scientist",
    person_or_company: "company",
    city: "irving",
  },
  {
    first_name: "John",
    last_name: "Hammergren",
    company: "McKesson",
    email: "johnnyBOI@mckesson.com",
    password: "JboI1233",
    profession: "Mobil Application",
    person_or_company: "company",
    city: "arlington",
  },
  {
    first_name: "Jeff",
    last_name: "Bezos",
    company: "Amazon",
    email: "JeffB@amazon.com",
    password: "Jbamazon1233",
    profession: "Full Stack Developer",
    person_or_company: "company",
    city: "seattle",
  },
  {
    first_name: "Sundar",
    last_name: "Pichai",
    company: "Google",
    email: "SundarP@amazon.com",
    password: "Googleis1",
    profession: "Data Scientist",
    person_or_company: "company",
    city: "mountain view",
  },
  {
    first_name: "Brandon",
    last_name: "Snyder",
    email: "brandon.snyder019@gmail.com",
    password: "root123",
    profession: "Full Stack Developer",
    person_or_company: "person",
    city: "Atlanta",
  },
  {
    first_name: "Carrington",
    last_name: "Edmondson",
    email: "mcarringtone@gmail.com",
    password: "root123",
    profession: "Full Stack Developer",
    person_or_company: "person",
    city: "Decatur",
  },
  {
    first_name: "James",
    last_name: "Edwards",
    email: "edwards.econn@gmail.com",
    password: "root123",
    profession: "Full Stack Developer",
    person_or_company: "person",
    city: "Newnan",
  },
  {
    first_name: "Eric",
    last_name: "Hurst",
    email: "Ericahurst77@gmail.com",
    password: "root123",
    profession: "Full Stack Developer",
    person_or_company: "person",
    city: "Suwanee",
  },
  {
    first_name: "Peter",
    last_name: "Piper",
    email: "PeterPiper@gmail.com",
    password: "TheRealPiper",
    profession: "Data Scienctist",
    person_or_company: "person",
    city: "Atlanta",
  },
  {
    first_name: "Richard",
    last_name: "Hendricks",
    email: "EricH@piedpiper.com",
    password: "root123",
    profession: "Data Scientist",
    person_or_company: "person",
    city: "Los Angeles",
  },
  {
    first_name: "Gilfoyle",
    last_name: "Starr",
    email: "TheRealG@piedpiper.com",
    password: "root123",
    profession: "Artificial intelligence",
    person_or_company: "person",
    city: "Los Angeles",
  },
  {
    first_name: "Dinesh",
    last_name: "Nanjiani",
    email: "MrStealYourGirl@piedpiper.com",
    password: "root123",
    profession: "Artificial intelligence",
    person_or_company: "person",
    city: "Los Angeles",
  },
];
const seedUser = () => User.bulkCreate(usersData);

module.exports = seedUser;
